defaults:
    - _self_
    - hydra: settings
    - observations: merit_forward


## General -------------------------------#
mode: predict  # train, test, train_test, predict
multimodel_type: none
random_seed: 111111
device: cuda
gpu_id: 5

data_loader: MsHydroLoader
data_sampler: MsHydroSampler
trainer: MsTrainer

save_path: ./results
trained_model: '' #/projects/mhpi/leoglonz/project_silmaril/dMG/results/merit_forward/train1980-1995/no_multi/LstmMlpModel_E100_R365_B100_H64_4096_n4_noLn_WU_111111/HBV_2_0/RmseCombLoss/3dyn/parBETA_parK0_parBETAET/dHBV_2_0_Ep100_original.pt


## Training ------------------------------#
train:
    # NOTE: Multiscale training for dHBV2.0 is not currently enabled in dMG.
    # Training code will be released at a later time.
    start_time: 1980/10/01
    end_time: 1995/09/30
    target: [streamflow]
    optimizer: Adadelta
    batch_size: 100
    epochs: 100
    start_epoch: 0
    save_epoch: 7


## Evaluation -------------------------------#
test:
    start_time: 1980/01/01
    end_time: 2020/12/31
    batch_size: 400
    test_epoch: 100


## Inference -------------------------------#
predict:
    start_time: 1980/01/01
    end_time: 1985/12/31
    batch_size: 200


## Loss Function -------------------------#
loss_function:
    model: RmseCombLoss


## dPL Model -----------------------------#
dpl_model:
    rho: 365
    
    phy_model:
        model: [HBV_2_0]  # HBV, HBV_1_1p, HBV_adj
        nmul: 2
        warm_up: 0
        warm_up_states: True
        dy_drop: 0.0
        dynamic_params:
            HBV: [parBETA, parBETAET]
            HBV_adj: [parBETA, parFC, parBETAET]
            HBV_1_1p: [parBETA, parK0, parBETAET]
            HBV_2_0: [parBETA, parK0, parBETAET]

        routing: True
        AD_efficient: True  ## Specific for HBV_adj
        use_log_norm: []
        nearzero: 1e-5

        forcings: [
            P,
            Temp,
            PET,
        ]
        attributes: []

    nn_model:
        model: LstmMlpModel

        lstm_dropout: 0.5
        lstm_hidden_size: 64

        mlp_dropout: 0.5
        mlp_hidden_size: 4096

        learning_rate: 1.0
        lr_scheduler: None
        lr_scheduler_params:
            step_size: 10
            gamma: 0.5
        
        forcings: [
            P,
            Temp,
            PET,
        ]
        attributes: [
            ETPOT_Hargr,
            FW,
            HWSD_clay,
            HWSD_gravel,
            HWSD_sand,
            HWSD_silt,
            NDVI,
            Porosity,
            SoilGrids1km_clay,
            SoilGrids1km_sand,
            SoilGrids1km_silt,
            T_clay,
            T_gravel,
            T_sand,
            T_silt,
            aridity,
            glaciers,
            meanP, 
            meanTa,
            meanelevation,
            meanslope,
            permafrost,
            permeability,
            seasonality_P,
            seasonality_PET, 
            snow_fraction,
            snowfall_fraction,
            uparea,
        ]
