name: Pytests

on:
  push:
    branches:
      - master
      - dmg_dev
      - dmg_ngen
  pull_request:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and test
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        source .venv/bin/activate
        uv pip install -e .
        uv pip install -e ".[dev, hydrodl2]"
        pytest
